### ISSUE TITLE
add css create unexpected text 'tab' that is postfixed with random number

### ISSUE THREAD

**Issue by dcao1123** [dreamRs/shinybusy#11]
Thanks for the nice package, 

when i use it, i always create a text 'tab-xxxx'

  add_busy_gif(
                 src = "https://jeroen.github.io/images/banana.gif", position = c( "top-right"),
                 # overlay_css ="z-index: 1000;",
                 margins=c(50,50),
                 height = 75, width = 75
               ),
<img width="887" alt="Annotation 2020-08-08 082124" src="https://user-images.githubusercontent.com/44759169/89710395-934b0600-d950-11ea-8ac2-a9f451e83252.png">

**Comment by pvictor** [comment]
Hello,

When using `navbarPage` you have to use the `header` argument, like this: 

```r
library(shiny)
library(shinybusy)

ui <- navbarPage(
  
  title = "My app",
  
  # Use in header argument
  header = tagList(
    add_busy_gif(
      src = "https://jeroen.github.io/images/banana.gif",
      height = 70, width = 70
    )
  ),
  
  tabPanel("Plot", actionButton("sleep", "Long calculation")),
  tabPanel("Summary"),
  tabPanel("Table")
  
)

server <- function(input, output, session) {
  
  observeEvent(input$sleep, {
    Sys.sleep(5)
  })
  
}

shinyApp(ui, server)
```

Victor

**Comment by dcao1123** [comment]
Hi Victor

Thank you! It worked.

Dongsun
