### ISSUE TITLE
add_busy_spinner not functioning post updating shinybusy from v0.2.0 to v0.2.1

### ISSUE THREAD

**Issue by Prashanthreddya** [dreamRs/shinybusy#12]
I had used add_busy_spinner in my application to display automatic loader, but that seems to have broken post updating shinybusy to v0.2.1. 

`add_busy_spinner(spin = "fading-circle", timeout = 500, position = "full-page", color = "#3c8dbc", width = "85px", height = "85px"),`

I get a blank screen instead of the loader now.

**Comment by pvictor** [comment]
Sorry for that, I'll fix it asap

Victor

**Comment by pvictor** [comment]
That's fixed in the GitHub version, please re-install with:

```r
remotes::install_github("dreamRs/shinybusy")
```

and try.

Victor

**Comment by Prashanthreddya** [comment]
Sure, thank you victor. Appreciate the help. By when would it be updated in the cran ?

**Comment by pvictor** [comment]
I'll try to do that by the end of the week

**Comment by pvictor** [comment]
Sorry for the delay, on CRAN now
