### ISSUE TITLE
`html_dependency_shinybusy` is deprecated

### ISSUE THREAD

**Issue by fzenoni** [dreamRs/shinybusy#23]
Hello, the command
```r
add_busy_gif(src = 'catjam.gif', height = 30, width = 30),
```
triggers the following warning in my Shiny application:
```
Warning in html_dependency_freezeframe() :
  `html_dependency_freezeframe` is deprecated and will be removed in next release.
```
The instructions are unclear. How should I update my code to make the warning go away?

**Comment by fzenoni** [comment]
The warning is gone as of v0.3.1

**Comment by pvictor** [comment]
Sorry for that, this was an internal mixup when updating JavaScript dependencies in 0.3.0.
