### ISSUE TITLE
Busy bar doesn't activate unless the user interacts with the app

### ISSUE THREAD

**Issue by melissagwolf** [dreamRs/shinybusy#7]
I'm using shinybusy but I'm running into an unfortunate conflict.  My app is running 500 reps of a monte carlo simulation, which is obviously time consuming.  I have an eventReactive statement, so when the user presses "go", I expect the busy bar to start moving.  Further, I have four tabs on my app (the first one is an instruction page, and the second one produces the results of the simulation).

If I simply add the busy bar to the code, it does not start moving automatically when the user presses go.  It only starts moving if the user clicks on the tab that the results appear in.

To get around this, I added an observeEvent statement and put the eventReactive with the monte carlo simulation in it.  This worked really well (the busy bar starts the second the user presses go).  However, if the user enters anything incorrectly that forces the model to fail to converge, the inclusion of observeEvent around the eventReactive statement force closes the app.

Do you have a suggestion for how I can work around this?  I am using flexdashboard, btw.

```
fluidPage(shinybusy::add_busy_bar(color = "#BECEE4"))
```
```
example < - eventReactive(input$go {
     #some function
})
```
```
observeEvent(input$go,{example()})
```

**Comment by pvictor** [comment]
Hello,

Maybe you can try using a lower timeout, e.g. :

```r
shinybusy::add_busy_bar(timeout = 100)
```

If it does not help, can you provide a reproducible example please ?

To deal with errors that break your app, you can try this function : https://dreamrs.github.io/shinyWidgets/reference/execute_safely.html

Victor

**Comment by melissagwolf** [comment]
That didn't work, unfortunately - the issue is that the busy bar doesn't start moving until the user clicks on the results tab (although the server is busy computing simulations).  If the user begins using the app with the results tab selected (instead of the instructions), the busy bar starts immediately.

Enter a random sample size to run:
```
---
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
always_allow_html: yes
---
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(simstandard)
library(lavaan)
library(tidyverse)
library(shinybusy)
```

```{r}
fluidPage(shinybusy::add_busy_bar(color = "#BECEE4"))
```
```
Sidebar {.sidebar}
=====================================

numericInput("sampsize", "Input Sample Size",value=NULL)

actionButton("go", "Submit")
```

```{r}
n <- eventReactive(input$go,{input$sampsize})
```

```{r}
example <- function(test){

  Sys.sleep(10)
  
  print("Hello")
  
}
```

```{r}
results <- eventReactive(input$go, {
  example(test)
})
```

```{r}
#Turn off because it crashes app
#observeEvent(input$go,{results()})
```
```
Results
=====================================  

Row {data-height=600, .tabset}
-----------------------------------------------------------------------
```
```
### Instruction Page

#Instructions
```
```
### Results Page

renderPrint({
  results()
})
```

**Comment by melissagwolf** [comment]
FYI - this seems to be a problem with shiny in general.  I think your package is accurate - the server does not start running until the user clicks on the "results" tab.  I have filed a bug report with shiny.
